language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
script:
  - asdf plugin-add boundary ./
  - asdf plugin-add consul ./
  - asdf plugin-add nomad ./
  - asdf plugin-add packer ./
  - asdf plugin-add serf ./
  - asdf plugin-add terraform ./
  - asdf plugin-add vault ./
  - asdf plugin-add waypoint ./
  - asdf list-all boundary | tail
  - asdf list-all consul | tail
  - asdf list-all nomad | tail
  - asdf list-all packer | tail
  - asdf list-all serf | tail
  - asdf list-all terraform | tail
  - asdf list-all vault | tail
  - asdf list-all waypoint | tail
  - asdf plugin-test boundary ./ 'boundary version'
  - asdf plugin-test consul ./ 'consul version'
  - asdf plugin-test nomad ./ 'nomad version'
  - asdf plugin-test packer ./ 'packer version'
  - asdf plugin-test serf ./ 'serf version'
  - asdf plugin-test terraform ./ 'terraform version'
  - asdf plugin-test vault ./ 'vault version'
  - asdf plugin-test waypoint ./ 'waypoint version'
os:
  - linux
  - osx
